import { ApplicationFrame } from '@moonbase/ui-components';
import { League_Spartan, Inter } from 'next/font/google';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['600', '700'],
  display: 'swap',
  variable: '--font-league-spartan',
});

const inter = Inter({
  subsets: ['latin'],
  display: 'swap',
  variable: '--font-inter',
});

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body
        className={`${leagueSpartan.variable} ${inter.variable} h1`}
        style={
          {
            '--bg-image': `url("${process.env.CUSTOM_BASE_PATH || ''}/bg.png")`,
          } as React.CSSProperties
        }
      >
        <ApplicationFrame>{children}</ApplicationFrame>
      </body>
    </html>
  );
}
