import { Topbar } from '@moonbase/ui-components';
import './global.css';

export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body>
      <Topbar></Topbar>
      {children}
      </body>
    </html>
  );
}
