import { Topbar } from '@moonbase/ui-components';
import { League_Spartan } from 'next/font/google'
import './global.css';


export const metadata = {
  title: 'Welcome to ',
  description: 'Generated by create-nx-workspace',
};

const leagueSpartan = League_Spartan({
  subsets: ['latin'],
  weight: ['600', '700'],
  display: 'swap',
})

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={leagueSpartan.className}>
      <Topbar></Topbar>
      {children}
      </body>
    </html>
  );
}
